print("Hello world!")
print("Thanvi")
print("Malla reddy university")
print("cse")
print("Srikalahasti")
print("Samsung A17")
print("27,000")
print("8 GB")
print("128 GB")
print("5000 mAh")
